{% set python_min = "3.12" %}
{% set name = "ribasim-api" %}
{% set version = "2026.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ribasim_api-{{ version }}.tar.gz
  sha256: 856ed9e43233997514f4edcf92cafa752cc26814403e540031213b25fae8952e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - xmipy >=1.3

test:
  imports:
    - ribasim_api
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://deltares.github.io/Ribasim/
  summary: Python bindings for libribasim
  dev_url: https://github.com/Deltares/Ribasim
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - FMSST
    - evetion
    - visr
    - Huite
