{% set python_min = "3.10" %}
{% set name = "ribasim-api" %}
{% set version = "2025.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ribasim_api-{{ version }}.tar.gz
  sha256: 6d24d16a0ca9279c26a8db3308c56ec9ef68d7803a137434f71907cb9c7926d9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - xmipy

test:
  imports:
    - ribasim_api
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://deltares.github.io/Ribasim/
  summary: Python bindings for libribasim
  dev_url: https://github.com/Deltares/Ribasim
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - deltares-service-account
    - Hofer-Julian
    - visr
    - Huite
