{% set python_min = "3.11" %}
{% set name = "ribasim-api" %}
{% set version = "2025.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ribasim_api-{{ version }}.tar.gz
  sha256: b880ff8c99885066473b4362a9cb9f2347d15fc88fad8a2aec7422fd83846413

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - xmipy >=1.3

test:
  imports:
    - ribasim_api
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://deltares.github.io/Ribasim/
  summary: Python bindings for libribasim
  dev_url: https://github.com/Deltares/Ribasim
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - deltares-service-account
    - Hofer-Julian
    - visr
    - Huite
