{% set name = "ribasim-api" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ribasim_api-{{ version }}.tar.gz
  sha256: 4ed564726ca1b812c5f2e0dd4d8d96b40510e905c6780ac279b1c22cca07f315

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61
    - pip
  run:
    - python >=3.10
    - xmipy

test:
  imports:
    - ribasim_api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://deltares.github.io/Ribasim/
  summary: Python bindings for libribasim
  dev_url: https://github.com/Deltares/Ribasim
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Hofer-Julian
    - visr
    - Huite
