{% set name = "ribasim-api" %}
{% set version = "2024.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ribasim_api-{{ version }}.tar.gz
  sha256: af2064b14c3dded5a440a67ecef334249ae3e6e5bd9f0c68fc4c2863a88a92c4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - xmipy

test:
  imports:
    - ribasim_api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://deltares.github.io/Ribasim/
  summary: Python bindings for libribasim
  dev_url: https://github.com/Deltares/Ribasim
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Hofer-Julian
    - visr
    - Huite
